"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
import yaml
from django.core.exceptions import ImproperlyConfigured

# import pymysql
# pymysql.install_as_MySQLdb()

BASE_DIR = Path(__file__).resolve().parent.parent
CONFIG_PATH = Path(os.environ.get("ROS_BUAA_CONFIG", BASE_DIR / "config.yaml"))
if CONFIG_PATH.exists():
    with CONFIG_PATH.open(encoding="utf-8") as config_file:
        CONFIG = yaml.safe_load(config_file) or {}
else:
    CONFIG = {}
if not isinstance(CONFIG, dict):
    raise ImproperlyConfigured("The configuration must be a YAML mapping.")

LOGFLAG = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or CONFIG.get("DjangoSecretKey", "")
if not SECRET_KEY:
    raise ImproperlyConfigured("Set DJANGO_SECRET_KEY or DjangoSecretKey in config.yaml.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CONFIG.get("Debug", False)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "se",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = ('*',)

# oss相关配置
OSS_SECRET_ID = CONFIG.get("OSS_SECRET_ID", "")
OSS_SECRET_KEY = CONFIG.get("OSS_SECRET_KEY", "")
OSS_ENDPOINT = CONFIG.get("OSS_ENDPOINT", "")
OSS_BUCKET_NAME = CONFIG.get("OSS_BUCKET_NAME", "")

# cos相关配置
COS_SECRET_ID = CONFIG.get("COS_SECRET_ID", "")
COS_SECRET_KEY = CONFIG.get("COS_SECRET_KEY", "")
COS_REGION = CONFIG.get("COS_REGION", "ap-beijing")
COS_BUCKET_NAME = CONFIG.get("COS_BUCKET_NAME", "")

# ros相关配置
ROS_HOST = CONFIG.get("ROSHOST", "127.0.0.1")
ROS_PORT = int(CONFIG.get("ROSPORT", 9090))
ROS_SERVICE_TIMEOUT = float(CONFIG.get("ROS_SERVICE_TIMEOUT", 5))

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY") or CONFIG.get("OPENROUTER_API_KEY", "")
OPENROUTER_MODEL = os.environ.get("OPENROUTER_MODEL") or CONFIG.get("OPENROUTER_MODEL", "qwen/qwen3-vl-8b-instruct")
OPENROUTER_TIMEOUT = float(CONFIG.get("OPENROUTER_TIMEOUT", 25))
