# Generated by Django 4.2.17 on 2025-05-04 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("oss_token", models.CharField(max_length=500)),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("init_x", models.FloatField(default=0.0)),
                ("init_y", models.FloatField(default=0.0)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="se.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "role",
                    models.IntegerField(choices=[(1, "管理员"), (0, "普通用户")], default=0),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_info", models.TextField(default="这个人很懒，什么都没有留下")),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.IntegerField(
                        choices=[(1, "发现明火"), (2, "发现垃圾"), (3, "发现陌生人"), (0, "其他")],
                        default=0,
                    ),
                ),
                ("detail", models.CharField(max_length=100)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="se.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("px", models.FloatField()),
                ("py", models.FloatField()),
                ("pz", models.FloatField()),
                ("ox", models.FloatField()),
                ("oy", models.FloatField()),
                ("oz", models.FloatField()),
                ("ow", models.FloatField()),
                (
                    "mmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="se.map"
                    ),
                ),
            ],
            options={"unique_together": {("mmap", "name")},},
        ),
    ]
