# Generated by Django 4.2.17 on 2025-05-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("se", "0002_face"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="password_hash", new_name="password",
        ),
    ]
