# Generated by Django 4.2.17 on 2025-06-01 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("se", "0003_rename_password_hash_user_password"),
    ]

    operations = [
        migrations.RenameField(model_name="map", old_name="init_x", new_name="x",),
        migrations.RenameField(model_name="map", old_name="init_y", new_name="y",),
        migrations.RemoveField(model_name="face", name="encodings",),
        migrations.RemoveField(model_name="user", name="user_info",),
        migrations.AddField(
            model_name="face",
            name="in_white_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="face",
            name="upload_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="log", name="x", field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="log", name="y", field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="log",
            name="event_type",
            field=models.IntegerField(
                choices=[(1, "发现明火"), (2, "发现烟雾"), (3, "发现陌生人"), (4, "发现垃圾")], default=0
            ),
        ),
    ]
